#!/bin/bash
set -euo pipefail

if [ "$#" -ne 2 ]; then
    echo "usage: $0 username groupname"
    exit 1
fi

NEW_USER="$1"
LDAP_GROUP="$2"

record="dn: cn=$LDAP_GROUP,ou=Group,dc=OCF,dc=Berkeley,dc=EDU
changetype: modify
add: memberUid
memberUid: $NEW_USER
"

echo "$record"
echo "====================="
read -rp "Add new record? [yN] " choice

if [ "$choice" != "y" ] && [ "$choice" != "yes" ]; then
    echo "Aborted."
    exit 0
fi

if ! ldapadd <<< "$record"; then
    echo "$NEW_USER added to $LDAP_GROUP"
else
    echo "An error occurred."
fi
