#!/bin/bash -e

[ "$#" -eq 1 ]  || (echo "usage: $0 [account]" >&2; exit 1)
[ "$(whoami)" == "root" ]  || (echo "You're not root." >&2; exit 1)
[ "$(hostname)" == "supernova" ] && echo "This would be much faster on the NFS host (homes.ocf.berkeley.edu)..."

user="$1"
passwd=$(getent passwd "$user") || (echo "Can't find that user." >&2; exit 2)
tmp=$(mktemp -d --suffix="-user-backup")
homedir=$(cut -d ':' -f6 <<< "$passwd")
webdir="/services/http/users/${user:0:1}/$user"

[ -d "$homedir" ] || (echo "Home directory doesn't exist." >&2; exit 3)
[ -d "$webdir" ] || (echo "Web directory doesn't exist." >&2; exit 3)

echo "Backing up to $tmp..."

echo "Making file backup..."
tar cfz - "$homedir" "$webdir" | pv | pigz > "$tmp/backup.tar.gz"

echo "Making SQL backup..."
/usr/local/bin/mysqldump-5.6 --defaults-file="/root/.my.cnf" --databases "$user" --single-transaction | \
    pv | pigz > "$tmp/backup.sql.gz"

echo "Done!"
