#!/bin/bash -e
if [ "$(hostname)" != "supernova" ]; then
	echo "you are not on supernova"
	exit 1
fi

sudo -u atool \
	env -i \
	PATH=/usr/sbin:/usr/bin:/bin \
		/opt/ocf/packages/create/create.py \
		--keytab /opt/create/private/create.keytab --admin-user create -i
