#!/usr/bin/env python3
"""Find the highest non-excluded OCF UID."""
import sys

from ocflib.infra.ldap import ldap_ocf
from ocflib.infra.ldap import OCF_LDAP_PEOPLE
from ocflib.account.creation import RESERVED_UID_RANGES
from ocflib.account.creation import IGNORED_UID_RANGES


def main():
    with ldap_ocf() as c:
        c.search(
            OCF_LDAP_PEOPLE, 
            '(uid=*)', 
            attributes=['uidNumber']
        )
    uids = [int(entry['attributes']['uidNumber']) for entry in c.response]
    remove_ranges = RESERVED_UID_RANGES + IGNORED_UID_RANGES
    uids = filter(lambda v: v not in remove_ranges, uids)
    print(f"Max currently used UID is: {max(uids)}")
    

if __name__ == "__main__":
    sys.exit(main())
