#!/usr/bin/env python3
"""Add a note about a user to User_Info."""

import argparse
import getpass
import pwd
import shutil
import sys
from datetime import date

from ocflib.misc.shell import yellow

USER_INFO = '/home/s/st/staff/User_Info'
USER_INFO_BAK = '/tmp/User_Info.bak.' + getpass.getuser()

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('-u', '--user', required=True, help='The username')
    parser.add_argument('-t', '--topic',
                        help='The topic of the note (e.g. sorry, website, etc.)')
    parser.add_argument('note', nargs=argparse.REMAINDER,
                        help='The note to add')
    args = parser.parse_args()

    user = args.user

    try:
        pwd.getpwnam(user)
    except KeyError:
        print('User does not exist in LDAP')
        return 3

    try:
        with open(USER_INFO, 'r') as file:
            lines = file.readlines()
    except IOError as e:
        print('Could not read User_Info:', e.strerror)
        return 4

    next_line = ' '.join(args.note)

    if args.topic is None:
        resp = input(yellow('You have not specified a topic. Are you sure you would like to continue? [yN] '))
        if resp not in {'y', 'yes'}:
            print('Cancelling.')
            return 7

    topic = args.topic or ''
    staff = getpass.getuser()
    today = date.today().strftime('%Y-%m-%d')

    lines.append(user + ':' + today + ':' + staff + ':' + topic + ':' + next_line + '\n')
    lines.sort()

    try:
        shutil.copy(USER_INFO, USER_INFO_BAK)
    except shutil.Error:
        print('Could not open backup for writing')
        return 6

    try:
        with open(USER_INFO, 'w') as file:
            for l in lines:
                file.write(l)
    except IOError as e:
        print('Could not write to User_Info:', e.strerror)
        return 5

    print('Note saved, a backup was saved in ' + USER_INFO_BAK)


if __name__ == "__main__":
    sys.exit(main())
