repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    sha: v0.9.5
    hooks:
    -   id: autopep8-wrapper
    -   id: check-added-large-files
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-xml
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: file-contents-sorter
    -   id: mixed-line-ending
    -   id: name-tests-test
    -   id: requirements-txt-fixer
    -   id: sort-simple-yaml
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.7.3'
    hooks:
    - id: flake8
      language_version: python3.5
-   repo: https://github.com/asottile/reorder_python_imports.git
    sha: v0.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    sha: v1.1.4
    hooks:
    -   id: remove-tabs
# TODO: Replace this with the actual repo
# (https://github.com/detailyang/pre-commit-shell)
# once it supports types and not just files ending in shell extensions
-   repo: local
    hooks:
    -   id: shell-lint
        name: Shell Syntax Check
        description: Check Shell Syntax on ALL staged files with user friendly messages and colors
        entry: shell-lint.sh
        language: script
        types: [executable, shell]
