#!/bin/bash
# Today featuring xargs abuse!

if [[ -z "$1" ]]; then
    echo "usage: deploy-symlinks target-directory"
    exit -1
fi

TARGET_DIR=$1

CREATED=0

if [[ ! -d $TARGET_DIR ]]; then
    echo "Creating target directory $TARGET_DIR"
    mkdir -p $TARGET_DIR
    CREATED=1
fi

if [[ $CREATED != 1 ]]; then
    read -p "Clearing target directory... ok? [yN] " choice
    case "$choice" in
        n|N ) echo "Okay :("; exit 0;;
        y|Y ) ;;
        * ) echo "Okay :("; exit 0;;
    esac

    rm -rf $TARGET_DIR/*
fi

EXECUTABLE=$(find . -executable -type f -not -path "./.git/*" -print0 | xargs -0 echo)

ITEMS=$(echo $EXECUTABLE | xargs -d " " -L 1 echo | wc -l)
ITEMS_UNIQ=$(echo $EXECUTABLE | xargs -d " " -L 1 basename | sort | uniq | wc -l)

if [[ $ITEMS -ne $ITEMS_UNIQ ]]; then
    echo "Error: duplicate script names. Yell at someone?"
    exit -1
fi

# How into xargs?
echo $EXECUTABLE | xargs -d " "  -L 1 readlink -f | xargs -L 1 -I {} ln -s {} $TARGET_DIR/
