#!/usr/bin/env python3
from argparse import ArgumentParser
from fcntl import flock
from fcntl import LOCK_EX
from fcntl import LOCK_NB
from fcntl import LOCK_UN

import yaml
from ocflib.lab.staff_hours import get_staff_hours
from ocflib.lab.staff_hours import STAFF_HOURS_FILE
from ocflib.misc.shell import edit_file


def main():
    parser = ArgumentParser()
    parser.add_argument('--path', '-p', default=STAFF_HOURS_FILE)
    args = parser.parse_args()

    content = None
    with open(args.path, 'r') as target:
        content = target.read()

    with open(args.path, 'r+') as target:
        try:
            flock(target.fileno(), LOCK_EX | LOCK_NB)
        except IOError:
            print('Somebody else is modifying this file!')
            exit(1)

        while True:
            content = edit_file(content)
            try:
                get_staff_hours(yaml.safe_load(content))
                # Note: if we get here, the file is valid.
                target.seek(0)
                target.write(content)
                target.truncate()
                break
            except (yaml.YAMLError, TypeError, KeyError):
                idunno = input('Syntax Error: Try again? [y/n] ')
                idunno = idunno.strip().lower()
                if idunno != 'y' and idunno != 'yes':
                    break
        flock(target.fileno(), LOCK_UN)


if __name__ == '__main__':
    main()
