#!/bin/bash -eu
if [[ "$(hostname)" != "supernova" && "$(hostname)" != "dev-supernova" ]]; then
    echo -e '\033[1;31mYou must run this command on supernova.\033[0m'
    exit 1
fi
sudo -u ocfeasyfilters /opt/share/utils/staff/gapps/easyfilters-real
