#!/usr/bin/env python3
"""Print DNS entries for domains we are configured to host for our users."""
import sys
from collections import namedtuple

from dns import resolver
from ocflib.vhost import application
from ocflib.vhost import mail
from ocflib.vhost import web
from tabulate import tabulate


Record = namedtuple('Record', ('domain', 'type', 'value'))


def _query(domain, record):
    return resolver.query(domain, record, raise_on_no_answer=False)


def main(username):
    domains = set()
    records = []

    for primary_domain, vhost_config in web.get_vhosts().items():
        if vhost_config['username'] == username:
            domains.add(primary_domain)
            domains.update(vhost_config['aliases'])

    for primary_domain, vhost_config in application.get_app_vhosts().items():
        if vhost_config['username'] == username:
            domains.add(primary_domain)
            domains.update(vhost_config['aliases'])

    for vhost in mail.get_mail_vhosts():
        if vhost.user == username:
            domains.add(vhost.domain)

    for domain in sorted(domains):
        try:
            answer = _query(domain, 'CNAME')
            if answer:
                records.append(Record(domain, 'CNAME', str(answer[0])))
                continue

            for type in ('A', 'AAAA', 'MX'):
                for rdata in _query(domain, type):
                    records.append(Record(domain, type, str(rdata)))
        except resolver.NXDOMAIN as n:
            records.append(Record(domain, 'NXDOMAIN', str(n)))

    headers = ('Domain', 'Type', 'Value')
    print(tabulate(records, headers))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        print('Usage: check-dns <username>')
        sys.exit(1)

    sys.exit(main(sys.argv[1]))
