#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo 'Usage: chsh [shell]'
    exit 1
fi

shell_choice=$1

ldif_template=$(cat <<EOL
dn: uid=$(whoami),ou=people,dc=ocf,dc=berkeley,dc=edu
changetype: modify
replace: loginShell
loginShell: $shell_choice
EOL
)

while read -r shell; do
    # Strip any whitespace from the shell path
    shell="${shell## }"
    shell="${shell%% }"

    # Check that the shell choice isn't commented out and is actually a valid
    # listed shell
    if [ "${shell:0:1}" != "#" ] && [ "$shell_choice" = "$shell" ]; then
        echo "Changing shell to $shell"
        /usr/bin/klist -t || /usr/bin/kinit

        # Apply the change to LDAP and silence the (rather verbose) output
        echo "$ldif_template" | ldapmodify -Q > /dev/null

        echo 'Shell successfully changed, typically it takes a while for the' \
             'changes to propagate to all our machines'

        exit 0
    fi
done < /etc/shells

echo "The shell you chose ($shell_choice) is not valid, please chose another"\
     'shell'

exit 1
