#!/usr/bin/env python2
from __future__ import print_function

import getpass
import os
import sys

import ldap
import ldap.modlist as modlist
import ldap.sasl as sasl

if len(sys.argv) < 2:
    print('Usage: chsh shell')
    sys.exit()

shell = sys.argv[1]
etcshells = open('/etc/shells', 'r')
line = etcshells.readline()
while line != '':
    validshell = line.strip()
    if shell == validshell:
        print('Changing shell to %s' % (validshell))
        kinit = '/usr/bin/klist -t || /usr/bin/kinit'
        os.system(kinit)
        conn = ldap.initialize('ldaps://ldap.ocf.berkeley.edu:636/')
        auth = sasl.gssapi('')
        conn.sasl_interactive_bind_s('', auth)
        dn = 'uid=%s,ou=people,dc=ocf,dc=berkeley,dc=edu' % (getpass.getuser())
        old = {'loginShell': '*'}
        new = {'loginShell': '%s' % (validshell)}
        ldif = modlist.modifyModlist(old, new)
        conn.modify_s(dn, ldif)
        conn.unbind_s()
        print('Shell successfully changed, typically it takes a while for the '
              'changes to propagate to all our machines')
        sys.exit()
    line = etcshells.readline()
print('The shell you chose is not valid, please chose another shell')
