#!/bin/sh
echo "Unfortunately, your account has been disabled."

if [ -r ~/.sorry ]; then
    echo "The reason your account has been disabled is:"
    cat ~/.sorry
fi

echo
echo "Please contact OCF staff:"
echo "https://ocf.berkeley.edu/docs/contact/"

exit 1
