#!/bin/bash -e
if [ "$(whoami)" != "root" ]; then
	echo "You are not root."
	exit 1
fi

# copy default config files
mkdir -p /root/.config/apt-dater
for f in apt-dater.conf screenrc; do
	path="/root/.config/apt-dater/$f"
	if [ ! -e "$path" ]; then
		cp -v "/usr/share/doc/apt-dater/examples/${f}.example" "$path"
	fi
done

subnet='169.229.10.0/24'
exclude_hosts='169.229.10.1,169.229.10.253'
keytab='/root/apt-dater.keytab'
config='/root/.config/apt-dater/hosts.conf'

kinit -t "$keytab" apt-dater

cat /dev/null > "$config"

hosts="`nmap -sn -oG - --system-dns --exclude $exclude_hosts $subnet \
| grep ^Host | cut -d' ' -f3 | cut -f1 | tr -d '()' | sed 's/.ocf.berkeley.edu//gI'`"
echo '[ocf]' >> "$config"; echo -n 'Hosts=' >> "$config"
for host in $hosts; do
  echo -n "apt-dater@$host;"
done >> "$config"

apt-dater -r > /dev/null
apt-dater
