#!/bin/bash
set -euo pipefail

TMPDIR="$(mktemp -d)"
trap 'cd / && rm -rf "$TMPDIR"' EXIT
cd "$TMPDIR"

# Download and launch Java firewall config client
curl --insecure https://firewall.ocf.berkeley.edu/admin/public/startup.jnlp > startup.jnlp
javaws startup.jnlp
