#!/bin/bash
set -euo pipefail

if [ $# -lt 1 ] || [ "$1" = "-h" ] || [ "$1" = "--help" ]; then
    echo "Usage: $0 stream"
    echo
    echo "Write stdin logs to OCF's remote syslog server."
    echo
    echo "You can use arbitrary stream names (without configuring them before); each"
    echo "stream will show up at syslog:/var/log/remote/<stream>.log."
    exit 1
fi

stream="$1"

grep -qE '^[a-z0-9_][-a-z0-9_]+$' <<< "$stream" || {
    echo "$0: invalid stream name."
    exit 2
}

exec logger -d -n syslog -P 514 -t "$stream"
