#!/bin/bash
set -euo pipefail

if [ $# -lt 1 ] || [ "$1" = "-h" -o "$1" = "--help" ]; then
    echo "Usage: $0 stream

Write stdin logs to OCF's remote syslog server.

You can use arbitrary stream names (without configuring them before); each
stream will show up at syslog:/var/log/remote/<stream>.
"
    exit 1
fi

stream="$1"

grep -qE '^[a-z0-9_][-a-z0-9_]+$' <<< "$stream" || {
    echo "$0: invalid stream name."
    exit 2
}

# Sorry, but this was the quickest and easiest way to do it and it works well
# enough for our purposes...
if [ $(lsb_release -cs) != "jessie" ]; then
    exec logger -T -n syslog -P 514 -t "$stream"
else
    # logger in jessie is broken, so we have to do it this way:
    while read line; do
        logger -T -n syslog -P 514 -t "$stream" <<< "$line"
    done
    if [ -n "$line" ]; then
        logger -T -n syslog -P 514 -t "$stream" <<< "$line"
    fi
fi
