#!/usr/bin/env python3
# This script is used to generate the Apache virtual host configuration.
import os.path
import ocflib.account.utils as utils

TEMPLATE_VHOST = """<VirtualHost *:{port}>
    ServerName {domain}
    ServerAdmin {user}@ocf.berkeley.edu
    DocumentRoot {docroot}
    UserDir disable
{config}
</VirtualHost>"""

FRAGMENT_SSL = """
    SSLEngine on
    SSLCertificateFile /etc/ssl/private/vhosts/{domain}.crt
    SSLCertificateKeyFile /etc/ssl/private/vhosts/{domain}.key
    SSLCertificateChainFile /etc/ssl/private/vhosts/{domain}.chain
    Include ssl-common.conf"""

FRAGMENT_HSTS = """
    Header set Strict-Transport-Security 'max-age=31536000'"""

FRAGMENT_MAIN = """
    SuexecUserGroup {user} ocf
    suPHP_Engine off
    Action php5-fcgi /php5-fcgi
    Alias /php5-fcgi /opt/suexec/{user}/php5-fcgi-wrapper

    <FilesMatch "\.ph(p3?|tml)$">
        SetHandler php5-fcgi
    </FilesMatch>

    <Directory /opt/suexec/{user}/>
        SetHandler fastcgi-script
    </Directory>

    <Directory {docroot}>
        AllowOverride All
        Options MultiViews SymLinksIfOwnerMatch IncludesNoExec ExecCGI

        AddHandler cgi-script cgi pl cgi-debug py

        <Limit GET POST OPTIONS PROPFIND>
            Order allow,deny
            Allow from all
        </Limit>
        <LimitExcept GET POST OPTIONS PROPFIND>
            Order deny,allow
            Deny from all
        </LimitExcept>
    </Directory>

    <Directory {docroot}cgi-bin/>
        Options -All
    </Directory>"""


def get_config(domain, config):
    """Returns string representing Apache <VirtualHost> block(s).

    A single vhost can expand to multiple actual blocks if the vhost has
    aliases which redirect to the primary host.
    """
    docroot = os.path.join(utils.web_dir(config['username']), config['docroot'][1:])
    if not docroot.endswith('/'):
        docroot += '/'

    primary_ssl = 'ssl' in config['flags']
    primary_port = 443 if primary_ssl else 80
    primary_url = "{proto}://{domain}/".format(
        proto='https' if primary_ssl else 'http',
        domain=domain)

    def wrap_vhost(domain, port, text):
        """Wraps the given config text inside a <VirtualHost> block, with
        appropriate settings for server name, admin, etc."""

        return TEMPLATE_VHOST.format(
            domain=domain,
            port=port,
            user=config['username'],
            docroot=docroot,
            config=text)


    def gen_redirect_config(host, port, redirect):
        return wrap_vhost(host, port, "    Redirect " + redirect)


    def gen_main_config(host):
        conf = FRAGMENT_MAIN.format(user=config['username'],
                                    docroot=docroot)

        if primary_ssl:
            conf += FRAGMENT_SSL.format(domain=domain)

            if 'hsts' in config['flags']:
                conf += FRAGMENT_HSTS

        return wrap_vhost(host, primary_port, conf)


    def get_fragments():
        yield "# {domain} ({user})".format(domain=domain, user=config['username'])

        if not config['redirect']:
            yield gen_main_config(domain)
        else:
            yield gen_redirect_config(domain, primary_port, config['redirect'])

        # add redirects (aliases and non-ssl)
        redirect_path = 'permanent / ' + primary_url

        for alias in config['aliases']:
            yield gen_redirect_config(alias, 80, redirect_path)

        if primary_ssl:
            yield gen_redirect_config(domain, 80, redirect_path)

    return "\n".join(get_fragments())


if __name__ == '__main__':
    vhosts = utils.get_vhosts().items()
    config = "\n\n".join(get_config(domain, conf) for domain, conf in vhosts)

    with open('/etc/apache2/sites-enabled/virtual.conf', 'w') as f:
        print(config, file=f)
