#!/bin/sh -e

suexecdir=/opt/suexec
wrapper=php5-fcgi-wrapper
users="`grep 'ServerAdmin [a-z].*@ocf.berkeley.edu' \
/etc/apache2/sites-enabled/virtual.conf | awk '{print $2}'| cut -d'@' -f1 | \
sort -u`"

cat > $suexecdir/$wrapper.c <<EOF
#include <stdio.h>
// php5-cgi wrapper that passes environment variable 
void main(){
  char *filename = "/usr/bin/php5-cgi";
  char *argv[] = { NULL };
  char *envp[] = { "PHP_FCGI_MAX_REQUESTS=10000" };
  execve(filename, argv, envp);
}
EOF

gcc -o $suexecdir/$wrapper $suexecdir/$wrapper.c
chmod 755 $suexecdir/$wrapper

for user in $users; do
  userdir=$suexecdir/$user
  mkdir -p $userdir
  cp $suexecdir/$wrapper $userdir/$wrapper
  chmod -R 0755 $userdir
  chown -R $user:ocf $userdir
done
