#!/bin/bash
# Generates email to hostmaster asking for CNAMEs in berkeley.edu
# Should be run on pestilence

echo "Hi hostmaster,"
echo ""
echo "Happy $(date +%A). Can you please add the following records to the DNS?"
echo ""

grep "IN A" /etc/bind/db.ocf | \
	egrep -v "@|go-away|try-next|deforestation|logjam|mgmt|dhcp" | \
	cut -d'	' -f1 | sort |
while read HOST; do
	host "$HOST.berkeley.edu" > /dev/null || \
		echo "$HOST.berkeley.edu. IN CNAME $HOST.ocf.berkeley.edu."
done

echo ""

if [ $(date +%u) -eq 5 ]; then
	echo "Have a great weekend!"
else
	echo "Thanks!"
fi

echo "$(getent passwd $USER | cut -d':' -f5 | cut -d' ' -f1)" # first name
