#!/bin/bash -e

if [ "$#" -ne 1 ]; then
	echo "usage: $0 fqdn"
	exit 1
fi

FQDN="$1"
KEY_SIZE=4096
KEY_PATH="$FQDN.key"

echo "Creating key $KEY_PATH..."

umask u=rw,go=
openssl genrsa -out "$KEY_PATH" "$KEY_SIZE"
openssl req -new -key "$KEY_PATH" -subj "/CN=$FQDN"
