#!/bin/bash
set -euo pipefail

echo "The following files were group or world writable:"

# Find group/world-writable files in /home and /services/http owned by group
# ocf. Remove the group- and world-writable bits on these files.
# However, don't bother searching in directories that normal users other than
# the directory's owner cannot access.
find /home /services/http \
     -type d \! -perm -go+x -prune \
     -o -group ocf -perm -go+w \! -type l \
        -exec chmod go-w {} + -print
