#!/usr/bin/env python3
import os
from subprocess import call
from sys import exit

import meetings
from ocflib.misc.shell import get_editor

# note that bod (which is stored in public_html, as they are publicly
# readable) is symlinked in this folder

# bod template file


def main():

    path = os.path.expanduser('~staff/minutes')
    options = os.listdir(path)

    print('What are you taking notes for?')
    print('Options:', ', '.join(options))

    choice = input()
    if choice not in options:
        return(0)

    path = os.path.join(path, choice)

    name = meetings.get_minutes_file()

    notes = os.path.join(meetings.get_current_minutes_path(choice), name)

    meetings.minutes_setup(notes, choice)

    call([get_editor(), notes])

    meetings.minutes_done(notes, choice)


if __name__ == '__main__':
    exit(main())
