#!/bin/sh

# TODO: Change to new share when on new puppetmaster
PRIV_SHARE="/opt/puppet/shares/private"

read -p 'Your username: ' user
echo 'List of hosts (leave off domain) to generate principals for, separated by spaces:'
read hostnames

cd $PRIV_SHARE
for host in $hostnames; do
  mkdir -p $host
  echo "Creating host/$host.ocf.berkeley.edu principal"
  kadmin -p $user/admin add -r --use-defaults host/$host.ocf.berkeley.edu
  echo "Exporting host/$host.ocf.berkeley.edu keytab"
  rm -f $host/krb5.keytab
  kadmin -p $user/admin ext_keytab -k $host/krb5.keytab host/$host.ocf.berkeley.edu
done

chown -R puppet:puppet $PRIV_SHARE
chmod -R u=rX,g=,o= $PRIV_SHARE
