#!/bin/bash -e
# Update the OCF root password. We use a ridiculous number of hash iterations
# to make cracking the hashes way over-the-top impossible.

ROOT_PW_FILE="/opt/puppetlabs/shares/private/rootpw"

echo "########################################################"
echo "This will update the root password for ALL OCF MACHINES."
echo "    YOU PROBABLY SHOULD NOT BE RUNNING THIS COMMAND."
echo "########################################################"
echo
read -rp "Are you sure you want to do this? [yN] " answer

if [ "$answer" != "y" ]; then
    echo "Wise choice."
    exit 1
fi

HASH=$(mkpasswd -m sha-512 -R 65536 | tr -d '\n')

if [ -z "$HASH" ]; then
    echo "Didn't get a password?"
    exit 1
fi

echo -n "$HASH" > $ROOT_PW_FILE
chown puppet:puppet $ROOT_PW_FILE
chmod 600 $ROOT_PW_FILE
