#!/bin/sh
# Update the OCF root password. We use a ridiculous number of hash iterations
# to make cracking the hashes way over-the-top impossible.
mkpasswd -m sha-512 -R 65536 | tr -d '\n' > /opt/puppet/shares/private/rootpw
chown puppet:puppet /opt/puppet/shares/private/rootpw
chmod 600 /opt/puppet/shares/private/rootpw
