#!/usr/bin/env python3
from ocflib.lab.printing import get_toner
from ocflib.lab.printing import PRINTERS

if __name__ == '__main__':
    for printer in PRINTERS:
        cur, max = get_toner(printer)
        percent = (cur / max) * 100
        print('{}: printed={}, remaining={} ({}%)'.format(printer, cur, max - cur, percent))
