#!/opt/venvs/ocf-utils/bin/python3.7
from ocflib.printing.printers import get_toner
from ocflib.printing.printers import PRINTERS

if __name__ == '__main__':
    for printer in PRINTERS:
        cur, max = get_toner(printer)
        percent = (cur / max) * 100
        print('{}: printed={}, remaining={} ({}%)'.format(printer, cur, max - cur, percent))
