#!/usr/bin/env python3
import argparse
import random
import socket
import sys
import time
from subprocess import call
from subprocess import Popen


def unused_port():
    def used(port):
        s = socket.socket()
        try:
            s.bind(('127.0.0.1', port))
        except Exception:
            return True
        else:
            s.close()
            return False

    port = None
    while port is None or used(port):
        port = random.randint(10000, 65535)

    return port


def wait_for_port(host, port, timeout=5, ssh_proc=None):
    spent = 0
    while True:
        if ssh_proc and ssh_proc.poll():
            raise ChildProcessError('SSH exited too quickly. Maybe run kinit?')

        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            if s.connect_ex((host, port)) == 0:
                return
        time.sleep(0.1)
        spent += 0.1

        if spent > timeout:
            raise TimeoutError('Timed out after {} seconds.'.format(timeout))


def volume(args):
    cmd = 'export PULSE_SERVER=localhost; '

    if args.amount is not None:
        cmd += 'pactl set-sink-volume 0 {}%; '.format(args.amount)

    # thanks SO for awk tricks
    cmd += "pactl list sinks | awk '/Sink #0/{nr[NR+9]}; NR in nr' | cut -d' ' -f 6;"

    # tornado has 2 sinks, we default to sink 0 which is HDMI out to TV
    return call(('ssh', args.host, cmd))


def volume_in_range(val):
    x = int(val[1:]) if val[0] in ['+', '-'] else int(val)
    if x < 0 or x > 150:
        raise argparse.ArgumentTypeError('{} is not within the range [0, 150]'.format(val))
    return '-- ' + val if val[0] is '-' else val  # pactl doesn't like negatives


def connect(args):
    port = unused_port()
    proc = Popen(['ssh', '-N', '-o', 'ExitOnForwardFailure=yes',
                  '-o', 'BatchMode=yes',
                  '-L', '{}:localhost:5900'.format(port), args.host])
    try:
        wait_for_port('localhost', port, ssh_proc=proc)
        call(['xvncviewer', 'localhost:{}'.format(port)])
    finally:
        proc.terminate()
        proc.wait()


if __name__ == '__main__':
    commands = {
        'connect': connect,
        'volume': volume,
        'mute': volume,
    }
    parser = argparse.ArgumentParser(
        description='Control the OCF television.',
    )
    parser.add_argument('-H', '--host', type=str, default='tv')

    command_subparser = parser.add_subparsers(dest='command')

    subparser_connect = command_subparser.add_parser('connect', help='open a vnc instance to view the TV screen')

    subparser_volume = command_subparser.add_parser('volume', help='set the volume on the TV using PulseAudio')
    subparser_volume.add_argument('amount', type=volume_in_range, nargs='?',
                                  help='volume in percent between 0% and 150%.'
                                       '+/- a relative value is also allowed.')

    subparser_mute = command_subparser.add_parser('mute', help='mute the TV')
    # dirty hack so volume() can be reused
    subparser_mute.add_argument('--amount', default=0, help=argparse.SUPPRESS)

    if len(sys.argv) == 1:
        args = parser.parse_args(['connect'])
    else:
        args = parser.parse_args()  # default is sys.argv

    commands[args.command](args)
