#!/bin/bash
# Download and launch Java firewall config client
cd /tmp
wget -O- http://ocf.io/mirror/jre-8u5-linux-x64.tar.gz | tar xfz -
curl -4 --insecure https://firewall/admin/public/startup.jnlp > startup.jnlp
jre*/bin/javaws startup.jnlp
