#!/bin/bash

if [ $# -ne 0 ]; then
  echo "Usage: '$0'"
  exit 1
fi

USER_SERVICES="/services/http/users/${USER:0:1}/$USER"

create_symlink() {
    ln -v -s "$USER_SERVICES" ~/public_html
    chmod -v 755 "$USER_SERVICES"

    if [ $? -eq 0 ]; then
        echo
        echo "public_html folder has been created successfully."
    else
        echo
        echo "public_html folder was NOT created successfully."
    fi
}

if [[ -e "$HOME/public_html" ]]; then
    # Get the epoch time for renaming the old public_html link/folder
    EXT=$(date "+%s")

    if [[ -h "$HOME/public_html" ]]; then
        SYMLINK_PATH=$(readlink $HOME/public_html)

        if [[ "$SYMLINK_PATH" != "$USER_SERVICES" ]]; then
            echo "Your symbolic link public_html is incorrect"
            echo "Creating a new link and moving the old link to public_html.$EXT"
            mv public_html public_html.$EXT

            create_symlink
            exit 2
        else
            echo "public_html already exists"
            echo "Not creating symlink"
            exit 3
        fi
    else
        echo "A folder with data exists in $HOME/public_html"
        echo "Moving the old folder to public_html.$EXT"
        mv public_html public_html.$EXT

        create_symlink
        exit 4
    fi
else
    create_symlink
    exit 0
fi
