#!/bin/bash

if [ $# -ne 0 ]; then
  /bin/echo "Usage: '$0'"
  exit 1
fi

create_symlink() {
  /bin/ln -v -s /services/http/users/${USER:0:1}/$USER ~/public_html
  /bin/chmod -v 755 /services/http/users/${USER:0:1}/$USER
  if [ $? -eq 0 ]
  then
    /bin/echo
    /bin/echo "public_html folder has been created successfully."
  else
    /bin/echo
    /bin/echo "public_html folder was NOT created successfully."
  fi
}

ext=`/bin/date "+%s"`

if [[ -e $HOME/public_html ]]
then
    if [[ -h $HOME/public_html ]]
    then
        symlink_path=`readlink $HOME/public_html`

        if [[ $symlink_path !=  "/services/http/users/${USER:0:1}/$USER" ]]
        then
            /bin/echo "Your symbolic link public_html is incorrect"
            /bin/echo "Creating a new link and moving the old link to public_html.$ext"
            /bin/mv public_html public_html.$ext

            create_symlink

            exit 2
        else
            /bin/echo "public_html already exists"
            /bin/echo "Not creating symlink"
            exit 3
        fi

    else
        /bin/echo "A folder with data exists in $HOME/public_html"
        /bin/echo "Moving the old folder to public_html.$ext"
        /bin/mv public_html public_html.$ext

        create_symlink

                exit 4
    fi
else

    create_symlink

        exit 0
fi
