#!/bin/bash
printf "Type password: "
MYDIR="$(dirname "$(which "$0")")"

ssh -t lightning sudo apt-dater -nr |
	python -c 'import sys; _ = sys.stdin.read(); print _[_.index("<?"):-9]' |
	$MYDIR/parse_apt_dater.py |
	mail -E -s "Package updates" sm@ocf.berkeley.edu
