#!/opt/venvs/ocf-utils/bin/python3.7
# Small utility to just get the weather from wttr.in, since wego is kind of
# annoying to set up and install
import argparse
import sys

import requests


def get_weather(location):
    # ugly but need to fake the user agent to match curl,
    # otherwise we get html in our response
    headers = {'User-Agent': 'curl'}
    res = requests.get(WTTR_SERVER + location, headers=headers)
    if res.status_code == 200 and res.text != WTTR_ERROR:
        print(res.text)
    else:
        print('location not found')


def main(args):
    parser = argparse.ArgumentParser(description='Lookup the current weather')
    parser.add_argument('-l', '--location',
                        default=DEFAULT_LOCATION,
                        help='specify name of location to look up the weather')
    parsed_args = parser.parse_args(args=args)
    get_weather(parsed_args.location)


DEFAULT_LOCATION = 'Berkeley'
# we can always make one of our own using wego, but too lazy to set up right now
WTTR_SERVER = 'http://wttr.in/'
WTTR_ERROR = 'ERROR'

if __name__ == '__main__':
    main(sys.argv[1:])
